config/routes.rb
Rails.application.routes.draw do
  resources :top do
    get 'sub', on: :collection
  end
  resources :trainings
  devise_for :users
  root 'top#index'
  resources :crops
  resources :categories
  resources :surveys do
    get 'analysis', on: :collection
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # メールの送信BOXを表示させるためのルーティング
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 管理者用のルーティング
  namespace :admin do
    resources :users
    post 'guest_admin_sign_in', to: 'users#guest_admin_sign_in', as: 'guest_admin_sign_in'
  end  

  # ゲストログイン用（一般ユーザー）のルーティング
  post 'guest_sign_in', to: 'users#guest_sign_in'

end

app/models/training.rb
class Training < ApplicationRecord
  belongs_to :category
  belongs_to :crop
  
  validates :title, :content, presence: true
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  before_action :check_admin, except: %i(index show)
  before_action :set_training, only: %i(show edit update destroy)
  before_action :set_categories_and_crops, only: %i(new create update)
  before_action :authenticate_user!, except: %i(index show)
  
  # GET /trainings or /trainings.json
def index
  @trainings = Training.all.order(updated_at: :DESC)
  if params[:title].present?
    @trainings = @trainings.where("title LIKE ?", "%#{params[:title]}%")
  end
  if params[:crop_id].present?
    @trainings = @trainings.where(crop_id: params[:crop_id])
  end
  if params[:category_id].present?
    @trainings = @trainings.where(category_id: params[:category_id])
  end
  @trainings = @trainings.page(params[:page]).per(10)
end

  # GET /trainings/1 or /trainings/1.json
  def show
  end

  # GET /trainings/new
  def new
    @training = Training.new
    @categories = Category.all
    @crops = Crop.all  
  end

  # GET /trainings/1/edit
  def edit
    @categories = Category.all
    @crops = Crop.all  
  end

  # POST /trainings or /trainings.json
  def create
    @training = Training.new(training_params)

    respond_to do |format|
      if @training.save
        format.html { redirect_to training_url(@training), notice: "トレーニングデータが登録されました！" }
        format.json { render :show, status: :created, location: @training }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trainings/1 or /trainings/1.json
  def update
    respond_to do |format|
      if @training.update(training_params)
        format.html { redirect_to training_url(@training), notice: "トレーニングデータが更新されました！" }
        format.json { render :show, status: :ok, location: @training }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @training.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trainings/1 or /trainings/1.json
  def destroy
    @training.destroy

    respond_to do |format|
      format.html { redirect_to trainings_url, notice: "トレーニングデータが削除されました！" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_training
      @training = Training.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def training_params
      params.require(:training).permit(:title, :content, :category_id, :crop_id)
    end

    def set_categories_and_crops
      @categories = Category.all
      @crops = Crop.all  
    end

end

app/helpers/trainings_helper.rb
module TrainingsHelper
end

app/views/trainings/_form.html.erb
<%= form_with(model: training, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if training.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>エラーが発生したため送信することが出来ませんでした。</h2>
      <ul>
        <% training.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="table training-form">
    <thead>
      <tr>
        <th><%= form_title %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding-left: 18%">タイトル<br><br><%= form.text_field :title, style: "width:80%;", class: 'form-control training-input' %></td>
      </tr>
      <tr>
        <td style="padding-left: 18%">カテゴリー<br><br><%= form.collection_select :category_id, @categories, :id, :title, { include_blank: true }, { style: "width:40%;", class: 'form-control training-input' } %></td>
      </tr>
      <tr>
        <td style="padding-left: 18%">作物<br><br><%= form.collection_select :crop_id, @crops, :id, :title, { include_blank: true }, { style: "width:40%;", class: 'form-control training-input' } %></td>
      </tr>
      <tr>
        <td style="padding-left: 18%">内容<br><br><%= form.text_area :content, style: "width:80%;", class: 'form-control training-input', size: "65x5" %></td>
      </tr>
      <tr>
        <td>
          <div class="actions text-center mt-3">
            <%= form.submit "送信する", class: 'btn btn-primary' %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/trainings/edit.html.erb
<div class="training-form-container" style="max-width: 45%; margin: 0 auto;">
  <%= render 'form', training: @training, categories: @categories, crops: @crops, form_title: "トレーニングデータ編集" %>
</div>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'トレーニングデータを確認する', @training, class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'トレーニングデータ一覧', trainings_path, class: 'btn btn-outline-secondary custom-link' %>
</div>

app/views/trainings/index.html.erb
<div class="headline" style="max-width: 25rem; background-color: #ce7878;">
  <h3 class="text-center">トレーニングデータ一覧</h3>
</div>

<%= form_with(url: trainings_path, method: :get, local: true) do |form| %>
  <table class="table search-table mt-3" style="max-width: 600px;">
    <tr>
      <td style="text-align: center;">
        <%= form.label :title, "タイトル", class: 'form-label' %>
        <%= form.text_field :title, value: params[:title], name: "title", class: 'form-control' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= form.label :crop_id, "作物", class: 'form-label' %>
        <%= form.select :crop_id, Crop.all.pluck(:title, :id), selected: params[:crop_id], include_blank: true, name: "crop_id", class: 'form-control' %>
      </td>
      <td>
        <%= form.label :category_id, "カテゴリーの種類", class: 'form-label' %>
        <%= form.select :category_id, Category.all.pluck(:title, :id), selected: params[:category_id], include_blank: true, name: "category_id", class: 'form-control' %>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="text-center">
        <%= form.submit "検索", class: 'btn btn-secondary' %>
      </td>
    </tr>
  </table>
<% end %>

<table class="table table-striped data-list mt-4" style="max-width: 85%;">
  <thead style="color: #fff; background-color: #ce7878;">
    <tr>
      <th>タイトル</th>
      <th>カテゴリ</th>
      <th>作物</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @trainings.each do |training| %>
      <tr>
        <td><%= training.title %></td>
        <td><%= training.category.title %></td>
        <td><%= training.crop.title %></td>
        <td><%= training.updated_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td><%= link_to '詳細', training, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to '編集', edit_training_path(training), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to '削除', training, method: :delete, data: { confirm: '削除しますがよろしいですか?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination mt-4">
  <%= paginate @trainings %>
</div>

app/views/trainings/new.html.erb
<div class="training-form-container" style="max-width: 45%; margin: 0 auto;">
    <%= render 'form', training: @training, categories: @categories, crops: @crops, form_title: "トレーニングデータ新規登録" %>
</div>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'トレーニングデータ一覧', trainings_path, class: 'btn btn-outline-secondary custom-link' %>
</div>

app/views/trainings/show.html.erb
<table class="table table-striped training-info" style="max-width: 45%;">
  <thead>
    <tr>
      <th>トレーニングデータ詳細</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding-left: 5%"><strong>タイトル</strong><br><br><%= @training.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 5%"><strong>カテゴリー</strong><br><br><%= @training.category.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 5%"><strong>作物</strong><br><br><%= @training.crop.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 5%"><strong>内容</strong><br><br><%= safe_join(@training.content.split("\n"), tag(:br)) %></td>
    </tr>
    <tr>
      <td style="padding-left: 5%"><strong>更新日時</strong><br><br><%= @training.updated_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
  </tbody>
</table>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'トレーニングデータを編集する', edit_training_path(@training), class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'トレーニングデータ一覧', trainings_path, class: 'btn btn-outline-secondary custom-link' %>
</div>