config/routes.rb
Rails.application.routes.draw do
  resources :top do
    get 'sub', on: :collection
  end
  resources :trainings
  devise_for :users
  root 'top#index'
  resources :crops
  resources :categories
  resources :surveys do
    get 'analysis', on: :collection
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # メールの送信BOXを表示させるためのルーティング
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 管理者用のルーティング
  namespace :admin do
    resources :users
    post 'guest_admin_sign_in', to: 'users#guest_admin_sign_in', as: 'guest_admin_sign_in'
  end  

  # ゲストログイン用（一般ユーザー）のルーティング
  post 'guest_sign_in', to: 'users#guest_sign_in'

end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :user
  belongs_to :category
  belongs_to :crop

  validates :title, presence: true, length: { maximum: 200 }
  validates :is_useful, inclusion: [true, false]
  validates :is_request, inclusion: [true, false]

  scope :search_by_user_name, -> (query){ joins(:user).where("users.name LIKE ?", '%' + query + '%' ) }

  def self.category_ranking
    Survey.left_joins(:category).select('categories.id as category_id, categories.title as category_title, count(surveys.id) as surveys_count').group('categories.id').order('surveys_count DESC')
  end

  def self.crop_ranking
    Survey.left_joins(:crop).select('crops.id as crop_id, crops.title as crop_title, count(surveys.id) as surveys_count').group('crops.id').order('surveys_count DESC')
  end

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "crop_id", "title", "is_useful", "is_request", "user_name"]
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i(show edit update destroy)
  before_action :set_q, only: %i(index)
  before_action :check_admin, only: %i(index edit update show destroy analysis)

  # GET /surveys or /surveys.json
  def index
    @q = Survey.ransack(params[:q])
    @surveys = @q.result(distinct: true).all.order(created_at: :DESC).page(params[:page]).per(10)
    @surveys = @surveys.search_by_user_name(params[:q]&.[](:user_name)) if params[:q]&.[](:user_name).present?
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
    @categories = Category.pluck(:title, :id).prepend(["", ""])
    @crops = Crop.pluck(:title, :id).prepend(["", ""])
  end

  # GET /surveys/1/edit
  def edit
    @categories = Category.pluck(:title, :id).prepend(["", ""])
    @crops = Crop.pluck(:title, :id).prepend(["", ""])
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)
    @survey.user_id = current_user.id
    @categories = Category.pluck(:title, :id).prepend(["", ""])
    @crops = Crop.pluck(:title, :id).prepend(["", ""])

    respond_to do |format|
      if @survey.save
        # メール送信設定
        # if @survey.is_request == true
        #   SurveyMailer.with(to: "jimajapan.g3@gmail.com", name: "出島").notify_admin.deliver_now
        # end
        format.html { redirect_to root_path, notice: "アンケートが送信されました！" }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    @categories = Category.pluck(:title, :id).prepend(["", ""])
    @crops = Crop.pluck(:title, :id).prepend(["", ""])
    
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "アンケートが更新されました！" }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "アンケートが削除されました！" }
      format.json { head :no_content }
    end
  end

  def analysis
    @category_rankings = Survey.category_ranking
    @crop_rankings = Survey.crop_ranking
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:title, :is_useful, :is_request, :category_id, :crop_id, :user_id)
    end

    def set_q
      @q = Survey.ransack(params[:q])
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_with(model: survey, html: { class: 'needs-validation', novalidate: true }) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h2>エラーが発生したため送信することが出来ませんでした。</h2>
      <ul>
        <% survey.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <table class="table survey-form">
    <thead>
      <tr>
        <th><%= form_title %></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td style="padding-left: 18%">チャットボットへの質問内容<br><br><%= form.text_area :title, style: "width:80%;", class: 'form-control survey-input' %></td>
      </tr>
      <tr>
        <td style="padding-left: 18%">カテゴリー<br><br><%= form.select :category_id, categories, {}, style: "width:40%;", class: 'form-control survey-input' %></td>
      </tr>
      <tr>
        <td style="padding-left: 18%">作物<br><br><%= form.select :crop_id, crops, {}, style: "width:40%;", class: 'form-control survey-input' %></td>
      </tr>
      <tr>
        <td style="padding-left: 23%"><%= form.check_box :is_useful, class: 'form-check-input' %>チャットボットが役立った</td>
      </tr>
      <tr>
        <td style="padding-left: 23%">
          <%= form.check_box :is_request, class: 'form-check-input' %>コンサルタントに回答を依頼する
          <% if local_assigns[:show_consultant_message] %>
            <div id="consultant_message" class="consultant-message">
              <p>送信するボタンを押して<br>コンサルタントからの返答をお待ちください。</p>
            </div>
          <% end %>
        </td>
      </tr>
      <tr>
        <td>
          <div class="actions text-center mt-3">
            <%= form.submit "送信する", class: 'btn btn-primary' %>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>

app/views/surveys/analysis.html.erb
<div class="headline" style="width: 20rem; background-color: #5fa3b4;">
  <h3 class="text-center">アンケート分析</h3>
</div>

<div class="top-container container mt-4">
    <table class="table table-striped data-list" style="flex: 1; margin-right: 10%; text-align: center;">
      <thead style="background-color: #facaaa;">
        <tr>
          <th>カテゴリー</th>
          <th>累計質問数</th>
        </tr>
      </thead>
      <tbody>
        <% @category_rankings.each_with_index do |category_ranking, index| %>
          <tr>
            <td><%= link_to category_ranking.category_title, surveys_path(q: { category_id_eq: category_ranking.category_id }) %></td>
            <td><%= category_ranking.surveys_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <table class="table table-striped data-list" style="flex: 1; text-align: center;">
      <thead style="background-color: #aaf2c4;">
        <tr>
          <th>作物</th>
          <th>累計質問数</th>
        </tr>
      </thead>
      <tbody>
        <% @crop_rankings.each_with_index do |crop_ranking, index| %>
          <tr>
            <td><%= link_to crop_ranking.crop_title, surveys_path(q: { crop_id_eq: crop_ranking.crop_id }) %></td>
            <td><%= crop_ranking.surveys_count %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/surveys/edit.html.erb
<div class="survey-form-container" style="max-width: 45%; margin: 0 auto;">
  <%= render 'form', survey: @survey, categories: @categories, crops: @crops, form_title: "アンケートの編集" %>
</div>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'アンケートの詳細を確認する', @survey, class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'アンケート一覧', surveys_path, class: 'btn btn-outline-secondary custom-link' %>
</div>

app/views/surveys/index.html.erb
<div class="headline" style="width: 20rem; background-color: #5fa3b4;">
  <h3 class="text-center">アンケート一覧</h3>
</div>

<%= search_form_for @q do |f| %>
  <table class="table search-table mt-3" style="max-width: 800px;">
    <tr>
      <td>
        <div style="display: inline-flex">
          <%= f.label :user_name, 'ユーザー名', class: 'form-label', style: 'margin-right: 10px;' %>
          <%= f.search_field :user_name, value: params.dig(:q, :user_name), class: 'form-control', style: 'max-width: 60%;' %>
        </div>
      </td>
      <td>
        <div style="display: flex">
          <%= f.label :title_cont, '質問内容', class: 'form-label', style: 'margin-right: 5px;' %>
          <%= f.search_field :title_cont, class: 'form-control', style: 'max-width: 60%;' %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :category_id_eq, 'カテゴリー', class: 'form-label' %>
        <%= f.collection_select :category_id_eq, Category.all, :id, :title, include_blank: '', class: 'form-control' %>
      </td>
      <td>
        <%= f.label :crop_id_eq, '作物', class: 'form-label' %>
        <%= f.collection_select :crop_id_eq, Crop.all, :id, :title, include_blank: '', class: 'form-control' %>
      </td>
    </tr>
    <tr>
      <td>
        <%= f.label :is_useful_eq, 'チャットボットが役立った', class: 'form-label' %>
        <%= f.select :is_useful_eq, [['はい', true], ['いいえ', false]], include_blank: '', class: 'form-control' %>
      </td>
      <td>
        <%= f.label :is_request_eq, 'コンサルタントへ依頼', class: 'form-label' %>
        <%= f.select :is_request_eq, [['はい', true], ['いいえ', false]], include_blank: '', class: 'form-control' %>
      </td>
    </tr>
    <tr>
      <td colspan="2" class="text-center">
        <%= f.submit "検索", class: 'btn btn-secondary' %>
      </td>
    </tr>
  </table>
<% end %>

<table class="table table-striped data-list mt-4" style="max-width: 93%;">
  <thead style="color: #fff; background-color: #5fa3b4;">
    <tr>
      <th>ユーザー</th>
      <th>質問内容</th>
      <th>カテゴリ</th>
      <th>作物</th>
      <th>チャットボットに満足</th>
      <th>コンサルタントへ依頼</th>
      <th>投稿日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td width="9%"><%= link_to survey.user.name, admin_user_path(survey.user) %></td>
        <td width="20%"><%= survey.title %></td>
        <td width="8%"><%= survey.category.title %></td>
        <td width="8%"><%= survey.crop.title %></td>
        <td width="11%"><%= survey.is_useful ? 'はい' : 'いいえ' %></td>
        <td width="11%"><%= survey.is_request ? 'はい' : 'いいえ' %></td>
        <td width="12%"><%= survey.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td width="7%"><%= link_to '詳細', survey, class: 'btn btn-primary btn-sm' %></td>
        <td width="7%"><%= link_to '編集', edit_survey_path(survey), class: 'btn btn-warning btn-sm' %></td>
        <td width="7%"><%= link_to '削除', survey, method: :delete, data: { confirm: '削除しますがよろしいですか?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination mt-4">
  <%= paginate @surveys %>
</div>

app/views/surveys/new.html.erb
<div class="top-container container">
  <div class="iframe-container">
    <iframe src="https://app.chatsimple.ai/iframe23/9ae1ac39-0451-48f4-a50d-8746e55ee740/84e6fda3-d9db-4ba9-a33e-361d9c533368/28753881-214d-431d-894e-60757ed26f76" 
      height="508px" width="100%" title="Chatsimple" 
      style="display:block; margin:auto; border:none; border-radius:20px; box-shadow:0px 14px 28px 0px rgba(0,0,0,0.2);">
    </iframe>
  </div>

  <div class="survey-form-container">
    <%= render 'form', survey: @survey, categories: @categories, crops: @crops, form_title: "アンケート <i class='fa-solid fa-pen'></i>".html_safe, show_consultant_message: true %>
  </div>
</div>

app/views/surveys/show.html.erb
<table class="table table-striped survey-info" style="max-width: 45%;">
  <thead>
    <tr>
      <th>アンケート詳細</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style="padding-left: 12%"><strong>質問内容</strong><br><br><%= @survey.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>カテゴリー</strong><br><br><%= @survey.category.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>作物</strong><br><br><%= @survey.crop.title %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>チャットボットが役立った</strong><br><br><%= @survey.is_useful ? 'はい' : 'いいえ' %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>コンサルタントに依頼する</strong><br><br><%= @survey.is_request ? 'はい' : 'いいえ' %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>ユーザー名</strong><br><br><%= @survey.user.name %></td>
    </tr>
    <tr>
      <td style="padding-left: 12%"><strong>投稿日時</strong><br><br><%= @survey.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
  </tbody>
</table>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'アンケートを修正する', edit_survey_path(@survey), class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'アンケート一覧', surveys_path, class: 'btn btn-outline-secondary custom-link' %>
</div>