config/routes.rb
Rails.application.routes.draw do
  resources :top do
    get 'sub', on: :collection
  end
  resources :trainings
  devise_for :users
  root 'top#index'
  resources :crops
  resources :categories
  resources :surveys do
    get 'analysis', on: :collection
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # メールの送信BOXを表示させるためのルーティング
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 管理者用のルーティング
  namespace :admin do
    resources :users
    post 'guest_admin_sign_in', to: 'users#guest_admin_sign_in', as: 'guest_admin_sign_in'
  end  

  # ゲストログイン用（一般ユーザー）のルーティング
  post 'guest_sign_in', to: 'users#guest_sign_in'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :surveys, dependent: :destroy

  validates :name, presence: true
  validates :phone_number, presence: true
  validates :phone_number, presence: true, format: { with: /\A\+?\d+\z/, message: "は半角数字のみで入力してください" },
                                            length: { minimum: 10, maximum: 11, message: "は10桁または11桁で入力してください" }
  validate :phone_number_must_not_contain_hyphens
  validates :password, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:recoverable, :rememberable, :validatable

  before_destroy :ensure_at_least_one_admin_remains
  before_update :ensure_at_least_one_admin_remains_on_update
  
  def self.search_by_name(keyword)
    if keyword.present?
      where('name LIKE ?', "%#{keyword}%")
    else
      all
    end
  end

  private
  def ensure_at_least_one_admin_remains
    if admin?
      if User.where(admin: true).count <= 1
        errors.add(:base, "管理者が0人になるため削除できません")
        throw(:abort)
      end
    end
  end

  def ensure_at_least_one_admin_remains_on_update
    if admin_changed? && admin == false && User.where(admin: true).count <= 1
      errors.add(:base, "管理者が0人になるため権限を変更できません")
      throw(:abort)
    end
  end

  def phone_number_must_not_contain_hyphens
    if phone_number.present? && phone_number.match?(/-/)
      errors.add(:phone_number, "にハイフンは入れないでください")
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, except: %i(guest_admin_sign_in)
  before_action :check_admin, except: %i(guest_admin_sign_in)
  before_action :set_user, only: %i(show edit update destroy)

  def index
    if params[:keyword].present?
      @users = User.search_by_name(params[:keyword]).page(params[:page]).per(10).order(created_at: :DESC)
    else
      @users = User.page(params[:page]).per(10).order(created_at: :DESC)
    end
  end

  def show
  end

  def edit
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_url(@user), notice: 'アカウントが登録されました！'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: 'ユーザ情報が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_url, notice: 'ユーザが削除されました。'
    else
      redirect_to admin_users_url, alert: @user.errors.full_messages.to_sentence
    end
  end

  # ゲスト管理者としてログインするためのアクション
  def guest_admin_sign_in
    # ゲスト管理者ユーザーを見つける、もし存在しなければ作成する
    user = User.find_or_create_by!(name: "guest_admin", phone_number: "00000000000", email: 'guest_admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.admin = true
    end
    sign_in user
    redirect_to sub_top_index_path, notice: 'ゲスト管理者としてログインしました。'
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :phone_number, :password, :password_confirmation, :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: %i(guest_sign_in)
  before_action :set_user, only: %i(show edit update destroy)
  before_action :correct_user, only: %i(show edit update destroy)
  skip_before_action :authenticate_user!, only: %i(guest_sign_in)

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    @user = User.find(params[:id])
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
  
    if @user.update(user_params)
      bypass_sign_in(@user)
      redirect_to @user, notice: 'プロフィールが更新されました。'
    else
      render :edit
    end
  end
  
  def destroy
    @user.destroy
    redirect_to new_user_session_path, notice: 'アカウントが削除されました。'
  end

  # ゲスト一般ユーザーとしてログインするためのアクション
  def guest_sign_in
    guest_user = find_or_create_guest_user
    sign_in guest_user
    redirect_to new_survey_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    unless current_user == @user
      redirect_to root_path, alert: '他のユーザーの情報にアクセスすることはできません！'
    end
  end

  def user_params
    params.require(:user).permit(:admin, :phone_number, :email, :name, :password, :password_confirmation)
  end
end

def find_or_create_guest_user
  User.find_or_create_by!(email: 'guest@example.com') do |user|
    user.name = "guest"
    user.phone_number = "00000000000"
    user.password = SecureRandom.urlsafe_base64
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="user-form-container" style="max-width: 40%; margin: 0 auto;">
  <%= form_with(model: [:admin, @user], local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2>入力内容に誤りがあるため送信することが出来ませんでした。</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <table class="table user-form">
      <thead>
        <tr>
          <th>ユーザー情報の編集</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>名前<br><br><%= form.text_field :name, style: "width:75%;"%></td>
        </tr>
        <tr>
          <td>電話番号<br><br><%= form.text_field :phone_number, style: "width:75%;" %></td>
        </tr>
        <tr>
          <td>メールアドレス<br><br><%= form.email_field :email, style: "width:75%;" %></td>
        </tr>
        <tr>
          <td>パスワード（6文字以上）<br><br><%= form.password_field :password, autocomplete: "new-password", style: "width:75%;" %></td>
        </tr>
        <tr>
          <td>
            パスワード（確認用）<br><br><%= form.password_field :password_confirmation, autocomplete: "new-password", style: "width:75%;" %>
            <p id="password-match" style="color: red;"></p>
          </td>
        <tr>
          <td><%= form.check_box :admin %> 管理者権限</td>
        </tr>
        <tr>
          <td>
            <div class="actions text-center">
              <%= form.submit "更新する", class: 'btn btn-primary' %>
            </div>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'ユーザー情報を確認する', admin_user_path(@user), class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn btn-outline-secondary custom-link' %>
</div>

app/views/admin/users/index.html.erb
<div class="headline" style="width: 18rem; background-color: #717171;">
  <h3 class="text-center">ユーザー一覧</h3>
</div>

<%= form_with(url: admin_users_path, method: :get, local: true, html: { class: 'search-form mt-3' }) do |form| %>
  <table class="table search-table" style="max-width: 400px;">
    <tr>
      <td style="text-align: center;">
        <%= form.label :keyword, "ユーザー名" %>
        <%= form.text_field :keyword, value: params[:keyword], class: 'form-control' %>
      </td>
    </tr>
    <tr>
      <td class="text-center">
        <%= form.submit "検索", class: 'btn btn-secondary' %>
      </td>
    </tr>
  </table>
<% end %>

<table class="table table-striped data-list mt-4" style="max-width: 85%; background-color: #d1d1d1;">
  <thead style="color: #fff; background-color: #717171;">
    <tr>
      <th>名前</th>
      <th>電話番号</th>
      <th>メールアドレス</th>
      <th>登録日時</th> 
      <th>管理者権限</th> 
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td width="13%"><%= user.name %></td>
        <td width="13%"><%= user.phone_number %></td>
        <td width="20%"><%= user.email %></td>
        <td width="17%"><%= user.created_at.strftime('%Y-%m-%d %H:%M') %></td>
        <td width="13%"><%= user.admin ? "あり" : "なし" %></td>
        <td width="8%"><%= link_to '詳細', admin_user_path(user), class: 'btn btn-primary btn-sm' %></td>
        <td width="8%"><%= link_to '編集', edit_admin_user_path(user), class: 'btn btn-warning btn-sm' %></td>
        <td width="8%"><%= link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="pagination mt-4">
  <%= paginate @users %>
</div>

app/views/admin/users/new.html.erb
<h1>新規ユーザー登録</h1>

<%= form_with(model: [:admin, @user], local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>が発生しました:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, "名前" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone_number%>
    <%= form.text_field :phone_number %>
  </div>

    <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation, "パスワード確認" %>
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= form.label :admin, "管理者権限" %>
    <%= form.check_box :admin %>
  </div>

  <div class="actions">
    <%= form.submit "登録" %>
  </div>
<% end %>

<%= link_to '戻る', admin_users_path %>

app/views/admin/users/show.html.erb
<table class="table table-striped user-info" style="max-width: 40%; margin: 0 auto;">
  <thead>
    <tr>
      <th>ユーザー情報</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><strong>名前</strong><br><br><%= @user.name %></td>
    </tr>
    <tr>
      <td><strong>電話番号</strong><br><br><%= @user.phone_number %></td>
    </tr>
    <tr>
      <td><strong>メールアドレス</strong><br><br><%= @user.email %></td>
    </tr>
    <tr>
      <td><strong>管理者権限</strong><br><br><%= @user.admin ? "あり" : "なし" %></td>
    </tr>
    <tr>
      <td><strong>登録日時</strong><br><br><%= @user.created_at.strftime('%Y-%m-%d %H:%M') %></td>
    </tr>
  </tbody>
</table>

<div class="form-row justify-content-center mt-4">
  <%= link_to 'ユーザー情報を編集する', edit_admin_user_path(@user), class: 'btn btn-outline-secondary custom-link' %>
  <%= link_to 'ユーザー一覧', admin_users_path, class: 'btn btn-outline-secondary custom-link' %>
</div>