config/routes.rb
Rails.application.routes.draw do
  resources :top do
    get 'sub', on: :collection
  end
  resources :trainings
  devise_for :users
  root 'top#index'
  resources :crops
  resources :categories
  resources :surveys do
    get 'analysis', on: :collection
  end
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # メールの送信BOXを表示させるためのルーティング
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # 管理者用のルーティング
  namespace :admin do
    resources :users
    post 'guest_admin_sign_in', to: 'users#guest_admin_sign_in', as: 'guest_admin_sign_in'
  end  

  # ゲストログイン用（一般ユーザー）のルーティング
  post 'guest_sign_in', to: 'users#guest_sign_in'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorAgri</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <div class="nav-container">
        <% if user_signed_in? %>
          <div class="nav-top">
            <div class="nav-top-left">
              <%= link_to image_tag('corporate_logo2.webp', alt: 'agri', class: 'logo'), root_path %>
            </div>
            <div class="nav-top-right">
              <%= link_to new_survey_path, class: "nav-link" do %>
                <i class="fa-solid fa-robot" style="color: #5ec750"></i>
                チャットボット
              <% end %>
              <%= link_to user_path(current_user), class: "nav-link" do %>
                <i class="fa-solid fa-user"></i>
                プロフィール
              <% end %>
              <%= link_to top_index_path, class: "nav-link" do %>
                <i class="fa-solid fa-file"></i>
                アプリ説明
              <% end %>
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                ログアウト
              <% end %>
            </div>
          </div>
          <% if current_user&.admin? %>
            <div class="nav-bottom">
              <%= link_to surveys_path, class: "nav-link" do %>
                <i class="fa-solid fa-comment" style="color: #5fa3b4"></i>
                アンケート一覧
              <% end %>
              <%= link_to analysis_surveys_path, class: "nav-link" do %>
                <i class="fa-solid fa-ranking-star" style="color: #5fa3b4"></i>
                アンケート分析
              <% end %>
              <%= link_to trainings_path, class: "nav-link" do %>
                <i class="fa-solid fa-database" style="color: #ce7878"></i>
                トレーニングデータ一覧
              <% end %>
              <%= link_to new_training_path, class: "nav-link" do %>
                <i class="fa-solid fa-circle-plus" style="color: #ce7878"></i>
                トレーニングデータ新規
              <% end %>
              <%= link_to admin_users_path, class: "nav-link" do %>
                <i class="fa-solid fa-users"></i>
                ユーザー一覧
              <% end %>
              <%= link_to sub_top_index_path, class: "nav-link" do %>
                <i class="fa-solid fa-file"></i>
                管理者機能説明
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="nav-top">
            <div class="nav-top-left">
              <%= link_to image_tag('corporate_logo2.webp', alt: 'agri', class: 'logo'), root_path %>
            </div>
            <div class="nav-top-right">
              <%= link_to new_user_session_path, class: "nav-link" do %>
                <i class="fa-solid fa-right-to-bracket"></i>
                ログイン
              <% end %>
              <%= link_to new_user_registration_path, class: "nav-link" do %>
                <i class="fa-regular fa-user"></i>
                新規登録
              <% end %>
              <%= link_to top_index_path, class: "nav-link" do %>
                <i class="fa-solid fa-file"></i>
                アプリ説明
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <% if notice.present? %>
      <p id="notice" class="flash-message"><%= notice %></p>
    <% end %>
    <%= yield %>

    <footer class="footer">
      <div class="container text-center">
        <p class="copyright">&copy; 2024 DoctorAgri. All rights reserved.</p>
      </div>
    </footer>
  </body>
</html>